ardop_model:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    shoulder_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder_1_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    upper_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: upper_1_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    upper_2_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: upper_2_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    lower_1_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: lower_1_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    lower_2_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: lower_2_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    end_effector_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: end_effector_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    wheel_front_left_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wheel_front_left_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    wheel_front_right_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wheel_front_right_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    wheel_back_left_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wheel_back_left_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}

    wheel_back_right_joint_position_controller:
        type: effort_controllers/JointPositionController
        joint: wheel_back_right_joint
        pid: {p: 1.0, i: 1.0, d: 0.0}
